apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-techtrends
    spec:
      containers:
        - image: 124545/mytrend-repo:latest
          imagePullPolicy: Always
          name: python-techtrends
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: 3111
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3111
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      imagePullSecrets:
        - name: secret-docker