apiVersion: v1
kind: Service
metadata:
  name: python-techtrends
  namespace: sandbox
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4111
      targetPort: 3111
  selector:
    app: python-techtrends
