namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: 124545/mytrend-repo
  tag: latest
  imagePullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

containerPort: 3111

readinessProbe:
  path: /healthz
  port: 3111

livenessProbe:
  path: /healthz
  port: 3111
