namespace:
  name: stagging

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: 124545/mytrend-repo
  tag: latest
  imagePullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPort: 3111

readinessProbe:
  path: /healthz
  port: 3111

livenessProbe:
  path: /healthz
  port: 3111
